/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miguel
 */
public class IF_ELEGIR_PDF extends javax.swing.JPanel {

    /**
     * Creates new form IF_ELEGIR_PDF
     */
    public IF_ELEGIR_PDF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

  private void JB_ABRIRActionPerformed(java.awt.event.ActionEvent evt){
        String Text = "";
     try{
         JFileChooser fc =new JFileChooser(System.getProperty("home/"));
         fc.showOpenDialog(this);
         File Abrir = fc.getSelectedFile();
         if (Abrir!=null){
            FileReader Fichero= new FileReader(Abrir);
            String NOMBRE = Abrir.getName();
            JL_RUTA.setText(Abrir + "");
            BufferedReader leer = new BufferedReader (Fichero);
            while ((Text = leer.readline())!=null){
                
            }
            leer.close();
        }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
